name: MasterPluginControl
main: de.impelon.masterplugincontrol.MasterControlMain
version: 1.0.2
author: Impelon
website: https://github.com/Impelon/MasterPluginControl

commands:
  mpc:
    usage: Unknown! Try '/mpc help'
    description: Main MasterPluginControl-Plugin command
    
permissions:
  mpc.*:
    description: Allows all MasterPluginControl-Plugin commands